# Generated by Django 5.0.7 on 2024-08-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kknet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ice_cream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='reviews', to='kknet.icecream'),
        ),
    ]
